### ISSUE TITLE
add the possibility to ignore closing errors during close

### ISSUE THREAD

**Issue by BrunoBonacci** [piotr-yuxuan/closeable-map#3]
It would be good to be able to ignore errors during close at key level or for the whole map, like
``` Clojure
(closeable-map
    ^:closeable-map/ignore-errors
    {;; Kafka producers/consumers are java.io.Closeable
     :producer (kafka-producer config)
     :consumer (kafka-consumer config)

     ;; File streams are java.io.Closeable too
     :outfile (io/output-stream (io/file "/tmp/outfile.txt"))

     ;; some libs return a function which when called stop the server, like:
     :server ^closeable-map/fn (http/start-server (api config) (:server config))})
```

**Comment by piotr-yuxuan** [comment]
Hello, that's a great idea, indeed it would be nice to have it. I have added some draft code ([link](https://github.com/piotr-yuxuan/closeable-map/blob/f4002294bd6666d525c0fdcf807e11dad4bdbd1c/src/piotr_yuxuan/closeable_map.clj#L27)), implementation and tests will follow.

**Comment by piotr-yuxuan** [comment]
Actually I'm having an issue with getting the meta data passed down to children during the walk. I've attempted something with dynamic var and per-thread binding but to no avail. I'll look at it further.

**Comment by piotr-yuxuan** [comment]
Done :-)
